name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # equatable: ^2.0.6
  firebase_auth: ^4.17.0
  cloud_firestore: ^5.6.8
  # firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  # path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true