name: pizza_repository
description: The Repo that handles pizzas
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.6.8
  # equatable: ^2.0.6
  # firebase_auth: ^4.17.0
  # firebase_storage: ^11.6.0
  # rxdart: ^0.27.7
  # path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
